###############################################################################
#
#   Convex Drawings of GKM Graphs
#
###############################################################################

@doc raw"""
    is_weakly_convex_drawing(G::AbstractGKM_graph, positions::Vector{Vector{QQFieldElem}}) -> Bool

Test whether a drawing given by `positions` is weakly convex (*).

A drawing is *weakly convex* if for every vertex `v`, every other vertex `w`
satisfies `positions[w] - positions[v] ∈ C_v`, where `C_v` is the cone
generated by `{positions[u] - positions[v] : u ∈ neighbors(v)}`.
"""
function is_weakly_convex_drawing(G::AbstractGKM_graph, positions::Vector{Vector{QQFieldElem}})
  n = n_vertices(G.g)
  n <= 1 && return true

  for v in 1:n
    nbrs = all_neighbors(G.g, v)
    isempty(nbrs) && continue

    # Build cone from neighbor directions
    generators = [positions[u] - positions[v] for u in nbrs]
    gen_matrix = matrix(QQ, length(generators), length(generators[1]),
                        reduce(vcat, [transpose(g) for g in generators]))
    C_v = positive_hull(gen_matrix)

    for w in 1:n
      w == v && continue
      diff = positions[w] - positions[v]
      if !(diff in C_v)
        return false
      end
    end
  end
  return true
end

@doc raw"""
    is_strongly_convex_drawing(G::AbstractGKM_graph, positions::Vector{Vector{QQFieldElem}}) -> Bool

Test whether a drawing given by `positions` is strongly convex (**).

A drawing is *strongly convex* if for every pair `(v, w)` and every simple path
`P` from `v` to `w`, the vector `positions[w] - positions[v]` lies in the cone
`C_v^P` generated by those neighbor directions at `v` whose edge weights lie in
the subspace spanned by the weights along `P`.
"""
function is_strongly_convex_drawing(G::AbstractGKM_graph, positions::Vector{Vector{QQFieldElem}})
  n = n_vertices(G.g)
  n <= 1 && return true
  d = rank_torus(G)

  for v in 1:n
    for w in 1:n
      v == w && continue

      # Enumerate all simple paths from v to w
      paths = _all_simple_paths(G.g, v, w)

      for path in paths
        # Collect edge weights along the path
        path_weights = Vector{Vector{QQFieldElem}}()
        for idx in 1:(length(path) - 1)
          a, b = path[idx], path[idx + 1]
          e = has_edge(G.g, a, b) ? Edge(a, b) : Edge(b, a)
          we = [QQ(_w(G, e)[k]) for k in 1:d]
          push!(path_weights, we)
        end

        # Build subspace matrix from path weights (for rank test)
        H_matrix = matrix(QQ, length(path_weights), d,
                          reduce(vcat, [transpose(pw) for pw in path_weights]))

        # Find neighbors of v whose edge weight lies in the row space of H_matrix
        restricted_generators = Vector{Vector{QQFieldElem}}()
        for u in all_neighbors(G.g, v)
          e_vu = has_edge(G.g, v, u) ? Edge(v, u) : Edge(u, v)
          we_vu = [QQ(_w(G, e_vu)[k]) for k in 1:d]

          # Check if we_vu is in the row space of H_matrix
          if _in_row_space(we_vu, H_matrix)
            push!(restricted_generators, positions[u] - positions[v])
          end
        end

        # If no restricted generators, the cone is {0} — diff must be zero
        diff = positions[w] - positions[v]
        if isempty(restricted_generators)
          if !all(c -> c == 0, diff)
            return false
          end
          continue
        end

        gen_matrix = matrix(QQ, length(restricted_generators), length(diff),
                            reduce(vcat, [transpose(g) for g in restricted_generators]))
        C_v_P = positive_hull(gen_matrix)
        if !(diff in C_v_P)
          return false
        end
      end
    end
  end
  return true
end

"""
    _in_row_space(v::Vector{QQFieldElem}, M::QQMatrix) -> Bool

Check whether the vector `v` lies in the row space of `M`.
"""
function _in_row_space(v::Vector{QQFieldElem}, M::QQMatrix)
  d = length(v)
  # Stack v as an extra row and check if rank increases
  v_mat = matrix(QQ, 1, d, v)
  return rank(vcat(M, v_mat)) == rank(M)
end

"""
    _all_simple_paths(g::Graph, src::Int, dst::Int; max_paths::Int=10000) -> Vector{Vector{Int}}

Enumerate all simple paths from `src` to `dst` via DFS.
Returns at most `max_paths` paths; emits a warning if the limit is reached.
"""
function _all_simple_paths(g::Graph, src_v::Int, dst_v::Int; max_paths::Int=10000)
  paths = Vector{Vector{Int}}()
  stack = [(src_v, [src_v], Set{Int}([src_v]))]

  while !isempty(stack)
    (current, path, visited) = pop!(stack)
    if current == dst_v
      push!(paths, path)
      if length(paths) >= max_paths
        @warn "Path enumeration limit ($max_paths) reached for vertices $src_v → $dst_v"
        return paths
      end
      continue
    end
    for nbr in all_neighbors(g, current)
      if !(nbr in visited)
        push!(stack, (nbr, vcat(path, nbr), union(visited, Set([nbr]))))
      end
    end
  end
  return paths
end

@doc raw"""
    convex_drawing_representatives(G::AbstractGKM_graph; strong::Bool=false) -> Vector{Vector{Vector{QQFieldElem}}}

Return all admissible drawing representatives that are convex.

If `strong=false` (default), filters by weak convexity (*).
If `strong=true`, filters by strong convexity (**).
"""
function convex_drawing_representatives(G::AbstractGKM_graph; strong::Bool=false)
  reps = admissible_drawing_representatives(G)
  test = strong ? is_strongly_convex_drawing : is_weakly_convex_drawing
  return filter(pos -> test(G, pos), reps)
end
