export SmallEquivariantQuantumCohomology, SmallEquivariantQuantumClass
export small_equivariant_quantum_cohomology, quantum_class, QH_class
export quantum_coefficients, coefficient, truncation_degrees
export quantum_product
export small_quantum_cohomology_ring
