const CurveClass = AbstractAlgebra.Generic.FreeModuleElem{ZZRingElem}

function _max_n_edges(H2::GKM_H2, beta::CurveClass)
  return Int(floor(sum(H2.ray_sum[i] * beta[i] for i in 1:rank(H2.H2))))
end

function _multiplicities(H2::GKM_H2, edge_list::Vector{Edge}, beta::CurveClass)
  domain = free_module(ZZ, length(edge_list))
  edge_map = ModuleHomomorphism(domain, H2.edge_lattice,
    [gens(H2.edge_lattice)[H2.edge_to_gen[e]] for e in edge_list])
  class_map = compose(edge_map, H2.quotient)
  result = Set{Vector{Int}}()
  success, initial = has_preimage_with_preimage(class_map, beta)
  success || return result
  kernel_module, inclusion = kernel(class_map)
  polytope = polyhedron(-transpose(matrix(inclusion)), [initial[i] for i in eachindex(edge_list)])
  for point in interior_lattice_points(polytope)
    multiplicity = initial + inclusion(kernel_module([point[i] for i in 1:rank(kernel_module)]))
    all(i -> multiplicity[i] > 0, eachindex(edge_list)) || continue
    push!(result, Int[multiplicity[i] for i in eachindex(edge_list)])
  end
  return result
end

"""
    GKM_second_homology(G::AbstractGKMGraph) -> GKM_H2

Return the lattice generated by invariant curves modulo the
relations detected by the axial function. Orbifold relations use the actual
flag weights: primitive weights divided by their generic stabilizer orders.
"""
GKM_second_homology(G::AbstractGKMGraph)::GKM_H2 = G.H2

function _edge_list_and_indices(data::GKMCombinatorialData)
  edge_list = collect(edges(graph(data)))
  edge_to_gen = Dict{Edge,Int}()
  sizehint!(edge_to_gen, 2 * length(edge_list))
  for (i, e) in enumerate(edge_list)
    edge_to_gen[e] = i
    edge_to_gen[reverse(e)] = i
  end
  return edge_list, edge_to_gen
end

_homology_weight(data::GKMCombinatorialData, e::Edge) = [QQ(weight(data, e)[i]) for i in 1:rank_torus(data)]

function _homology_weight(data::GKMCombinatorialData{R,V,F}, e::Edge) where {R,V,F<:AbstractOrbifoldFlagWeight}
  stored_edge = haskey(data.edge_flags, e) ? e : reverse(e)
  source_flag = first(data.edge_flags[stored_edge])
  stabilizer = order_of_generic_stabilizer(flags(data, src(stored_edge))[source_flag])
  return [QQ(weight(data, e)[i]) / stabilizer for i in 1:rank_torus(data)]
end

function _common_homology_weight_denominator(data::GKMCombinatorialData, edge_list)
  result = ZZ(1)
  for e in edge_list, i in 1:rank_torus(data)
    coordinate = _homology_weight(data, e)[i]
    result = lcm(result, denominator(QQ(coordinate)))
  end
  return result
end

# Fundamental cycles of a spanning forest. This avoids computing a module
# kernel merely to find the integral first homology of the underlying graph.
function _fundamental_cycles(data::GKMCombinatorialData, edge_list::Vector{Edge}, edge_to_gen::Dict{Edge,Int})
  n = nv(graph(data))
  visited = falses(n)
  parent = zeros(Int, n)
  depth = zeros(Int, n)
  tree_edge = falses(length(edge_list))
  queue = Vector{Int}(undef, n)
  components = 0

  for root in 1:n
    visited[root] && continue
    components += 1
    visited[root] = true
    head = tail = 1
    queue[1] = root
    while head <= tail
      v = queue[head]
      head += 1
      for u in all_neighbors(graph(data), v)
        visited[u] && continue
        visited[u] = true
        parent[u] = v
        depth[u] = depth[v] + 1
        tree_edge[edge_to_gen[Edge(v, u)]] = true
        tail += 1
        queue[tail] = u
      end
    end
  end

  cycles = Vector{Vector{Edge}}()
  sizehint!(cycles, length(edge_list) - n + components)
  for (i, e) in enumerate(edge_list)
    tree_edge[i] && continue
    u, v = src(e), dst(e)
    cycle = Edge[e]
    u_branch = Edge[]
    while depth[v] > depth[u]
      p = parent[v]
      push!(cycle, Edge(v, p))
      v = p
    end
    while depth[u] > depth[v]
      p = parent[u]
      push!(u_branch, Edge(p, u))
      u = p
    end
    while u != v
      pv = parent[v]
      push!(cycle, Edge(v, pv))
      v = pv
      pu = parent[u]
      push!(u_branch, Edge(pu, u))
      u = pu
    end
    append!(cycle, Iterators.reverse(u_branch))
    push!(cycles, cycle)
  end
  return cycles
end

function _remove_homology_torsion(M::AbstractAlgebra.FPModule{ZZRingElem})
  normal_form, to_normal_form = snf(M)
  factors = normal_form.invariant_factors
  H2 = free_module(ZZ, count(iszero, factors))
  images = Vector{typeof(zero(H2))}(undef, length(factors))
  next_free = 1
  for i in eachindex(factors)
    if iszero(factors[i])
      images[i] = gens(H2)[next_free]
      next_free += 1
    else
      images[i] = zero(H2)
    end
  end
  normal_to_free = ModuleHomomorphism(normal_form, H2, images)
  return H2, compose(inv(to_normal_form), normal_to_free)
end

function _homology_chern_weight(data::GKMCombinatorialData, v::Int)
  result = zero(lattice(data))
  for i in eachindex(flags(data, v))
    result += weight(data, v, i)
  end
  return result
end

function _homology_chern_number(data::GKMCombinatorialData, e::Edge)::ZZRingElem
  difference = _homology_chern_weight(data, src(e)) - _homology_chern_weight(data, dst(e))
  edge_weight = weight(data, e)
  scalar = nothing
  for i in 1:rank_torus(data)
    if iszero(edge_weight[i])
      @req iszero(difference[i]) "Chern weights are not proportional to the edge weight"
    else
      value = difference[i] / edge_weight[i]
      isnothing(scalar) ? (scalar = value) : (@req scalar == value "Chern weights are not proportional to the edge weight")
    end
  end
  @req !isnothing(scalar) "The edge weight is zero"
  @req denominator(scalar) == 1 "The first Chern number is not integral"
  return ZZ(numerator(scalar))
end

function _zero_GKM_H2()
  M = free_module(ZZ, 0)
  quotient = ModuleHomomorphism(M, M, zero_matrix(ZZ, 0, 0))
  dual_cone = cone_from_inequalities(zero_matrix(QQ, 0, 0))
  integers = free_module(ZZ, 1)
  chern = ModuleHomomorphism(M, integers, zero_matrix(ZZ, 0, 1))
  return GKM_H2(M, M, Dict{Edge,Int}(), quotient, dual_cone, QQFieldElem[], chern)
end

function _GKM_second_homology(data::GKMCombinatorialData)::GKM_H2
  edge_list, edge_to_gen = _edge_list_and_indices(data)
  isempty(edge_list) && return _zero_GKM_H2()
  edge_lattice = free_module(ZZ, length(edge_list))
  lattice_gens = gens(edge_lattice)
  cycles = _fundamental_cycles(data, edge_list, edge_to_gen)
  common_denominator = _common_homology_weight_denominator(data, edge_list)
  relations = Vector{typeof(zero(edge_lattice))}()
  sizehint!(relations, rank_torus(data) * length(cycles))

  for cycle in cycles, coordinate in 1:rank_torus(data)
    relation = zero(edge_lattice)
    for e in cycle
      coefficient = common_denominator * QQ(_homology_weight(data, e)[coordinate])
      relation += ZZ(coefficient) * lattice_gens[edge_to_gen[e]]
    end
    iszero(relation) || push!(relations, relation)
  end

  relation_module, _ = sub(edge_lattice, relations)
  h2_with_torsion, q1 = quo(edge_lattice, relation_module)
  H2, q2 = _remove_homology_torsion(h2_with_torsion)
  quotient = compose(q1, q2)
  dual_cone, ray_sum, chern = _finish_GKM_H2(data, edge_lattice, H2, quotient, edge_list)
  return GKM_H2(edge_lattice, H2, edge_to_gen, quotient, dual_cone, ray_sum, chern)
end

function _finish_GKM_H2(data, edge_lattice, H2, quotient, edge_list)
  h2_rank = length(gens(H2))
  images = [quotient(gens(edge_lattice)[i]) for i in eachindex(edge_list)]
  @req all(!iszero, images) "Some invariant edge is zero in homology"
  inequalities = [[image[j] for j in 1:h2_rank] for image in images]
  dual_cone = cone_from_inequalities(-inequalities)
  @req dim(dual_cone) == h2_rank "The cone of invariant curves is not full-dimensional"
  ray_sum = reduce(+, rays(dual_cone))
  minimum_evaluation = minimum(sum(ray_sum[j] * image[j] for j in 1:h2_rank) for image in images)
  @req minimum_evaluation > 0 "The invariant curve cone is not strongly convex"
  ray_sum = inv(minimum_evaluation) * ray_sum

  integers = free_module(ZZ, 1)
  z = first(gens(integers))
  edge_chern = ModuleHomomorphism(edge_lattice, integers, [_homology_chern_number(data, e) * z for e in edge_list])
  chern = ModuleHomomorphism(H2, integers, [edge_chern(preimage(quotient, g)) for g in gens(H2)])
  return dual_cone, ray_sum, chern
end

@doc raw"""
    curve_class(G::AbstractGKMGraph, e::Edge) -> CurveClass
    curve_class(G::AbstractGKMGraph, src::String, dst::String)

Return the second homology class represented by the given edge whose source and destination have the given labels.

# Examples
```jldoctest curve_class
julia> P2 = projective_space(GKMGraph, 2);

julia> P2_blown_up = blow_up(subgraph_from_vertices(P2, [1]));

julia> P2_blown_up_ambient = ambient_graph(P2_blown_up);

julia> curve_class(P2_blown_up_ambient, "[1>3]", "[1>2]")
(-1, 1)
```
"""
function curve_class(G::AbstractGKMGraph, e::Edge)
  H2 = GKM_second_homology(G)
  return curve_class(H2, e)
end

curve_class(G::AbstractGKMGraph, source::String, destination::String) =
  curve_class(G, Edge(find_vertex_index(source, G), find_vertex_index(destination, G)))

function curve_class(H2::GKM_H2, e::Edge)
  @req haskey(H2.edge_to_gen, e) "Edge $e does not belong to the GKM graph"
  return H2.quotient(gens(H2.edge_lattice)[H2.edge_to_gen[e]])
end

function Oscar.is_effective(H2::GKM_H2, beta::CurveClass)::Bool
  @req parent(beta) === H2.H2 "The curve class must belong to H2.H2"
  return all(ray -> sum(beta[i] * ray[i] for i in 1:rank(parent(beta))) >= 0, rays(H2.dual_cone))
end

"""
    is_effective(G::AbstractGKMGraph, beta::CurveClass) -> Bool

Return whether `beta` is in the effective cone, i.e. whether it is a non-negative
linear combination of edge curve classes.
!!! note
    We consider the effective cone to be closed and hence zero is also considered effective.

# Examples
```jldoctest is_effective
julia> F3 = flag_variety(GKMGraph, [1, 1, 1]);

julia> beta = curve_class(F3, Edge(1, 2));

julia> is_effective(F3, beta)
true

julia> is_effective(F3, 0*beta)
true

julia> is_effective(F3, -1*beta)
false

julia> is_effective(F3, 2*beta)
true
```
"""
function Oscar.is_effective(G::AbstractGKMGraph, beta::CurveClass)::Bool
  return is_effective(G.H2, beta)
end

function Oscar.chern_number(H2::GKM_H2, beta::CurveClass; check::Bool=true)::ZZRingElem
  check && @req parent(beta) === H2.H2 "The curve class must belong to H2.H2"
  return H2.chern(beta)[1]
end

function Oscar.chern_number(G::AbstractGKMGraph, beta::CurveClass; check::Bool=true)::ZZRingElem
  return chern_number(G.H2, beta; check=check)
end

Base.show(io::IO, H2::GKM_H2) = print(io, "GKM curve classes in H_2")
function Base.show(io::IO, ::MIME"text/plain", H2::GKM_H2)
  print(io, "GKM curve classes: $(H2.H2)")
end

@doc raw"""
    print_curve_classes(G::AbstractGKM_graph)

For each edge, print the representative of its curve class and its Chern numner.

# Examples
```jldoctest print_curve_classes
julia> P2 = projective_space(GKMGraph, 2);

julia> print_curve_classes(P2)
2 -> 1: (1), Chern number: 3
3 -> 1: (1), Chern number: 3
3 -> 2: (1), Chern number: 3

julia> H5 = gkm_graph_of_toric(hirzebruch_surface(NormalToricVariety, 5));

julia> print_curve_classes(H5)
2 -> 1: (-5, 1), Chern number: -3
3 -> 2: (1, 0), Chern number: 2
4 -> 1: (1, 0), Chern number: 2
4 -> 3: (0, 1), Chern number: 7

julia> P2_blown_up = blow_up(subgraph_from_vertices(P2, [1]))
GKM subgraph of:
GKM graph with 4 nodes, valency 2 and axial function:
[1>3] -> [1>2] => (0, -1, 1)
2 -> [1>2] => (-1, 1, 0)
3 -> [1>3] => (-1, 0, 1)
3 -> 2 => (0, -1, 1)
Algorithmic connection for GKM graph with 4 nodes and valency 2
Subgraph:
GKM graph with 2 nodes, valency 1 and axial function:
[1>3] -> [1>2] => (0, -1, 1)
Algorithmic connection for GKM graph with 2 nodes and valency 1

julia> P2_blown_up_ambient = ambient_graph(P2_blown_up);

julia> print_curve_classes(P2_blown_up_ambient)
[1>3] -> [1>2]: (-1, 1), Chern number: 1
2 -> [1>2]: (1, 0), Chern number: 2
3 -> [1>3]: (1, 0), Chern number: 2
3 -> 2: (0, 1), Chern number: 3
```
"""
function print_curve_classes(G::AbstractGKMGraph)
  for e in edges(G)
    beta = curve_class(G, e)
    println("$(label(G, src(e))) -> $(label(G, dst(e))): $beta, Chern number: $(chern_number(G, beta))")
  end
  return nothing
end
